"""Project-wide constants — no business logic, only named literals."""
RESULT_HOME_WIN = 1
RESULT_DRAW = 0
RESULT_AWAY_WIN = -1

RESULT_LABELS = {
    RESULT_HOME_WIN: "Home Win",
    RESULT_DRAW: "Draw",
    RESULT_AWAY_WIN: "Away Win",
}

STATUS_FINISHED = "FINISHED"
STATUS_SCHEDULED = "SCHEDULED"

FOOTBALL_API_BASE = "https://api.football-data.org/v4"
ODDS_API_BASE = "https://api.the-odds-api.com/v4"

MIN_MATCHES_REQUIRED = 3
MAX_RETRY_ATTEMPTS = 3
RETRY_BACKOFF_SECONDS = 2
REQUEST_TIMEOUT_SECONDS = 30

KELLY_FRACTION = 0.25
MIN_CONFIDENCE_THRESHOLD = 0.55
MIN_VALUE_THRESHOLD = 0.02
MAX_KELLY_FRACTION = 0.10
DEFAULT_LEAGUE_AVG_GOALS = 1.35
DEFAULT_LEAGUE_AVG_HOME_GOALS = 1.50
DEFAULT_LEAGUE_AVG_AWAY_GOALS = 1.10
ELO_DEFAULT_RATING = 1500.0
ELO_K_FACTOR = 32
ELO_HOME_ADVANTAGE = 100